---
# tasks file for ansible-role-nginx

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ nginx_log_dir }}"
    mode: 0755
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: directory
  notify: Restart nginx

- name: Create db directory
  file:
    path: "{{ nginx_db_dir }}"
    mode: 0755
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: directory
  notify: Restart nginx

- name: Create nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file }}"
    validate: echo %s
  notify: Restart nginx

- name: Start nginx
  service:
    name: "{{ nginx_service }}"
    enabled: true
    state: started
